### ISSUE TITLE
Kahn's Algorithm

### ISSUE THREAD

**Issue by kapil4457** [Kumar-laxmi/Algorithms#457] opened 2023-01-24 12:21 UTC
**Is your feature request related to a problem? Please describe.**
I will be implementing Kahn's Algorithm in  C++.
**Describe the solution you'd like**

Step-1:  Compute in-degree (number of incoming edges) for each of the vertex present in the DAG and initialize the count of visited 
              nodes as 0.

Step-2:  Pick all the vertices with in-degree as 0 and add them into a queue (Enqueue operation)

Step-3:  Remove a vertex from the queue (Dequeue operation) and then. 
             Increment the count of visited nodes by 1.
             Decrease in-degree by 1 for all its neighbouring nodes.
             If the in-degree of neighbouring nodes is reduced to zero, then add it to the queue.

Step 4:  Repeat Step 3 until the queue is empty.

Step 5:  If the count of visited nodes is not equal to the number of nodes in the graph then the topological sort is not possible for the given graph.

**Additional context**

![1](https://user-images.githubusercontent.com/78656206/214290308-09672c5f-cd64-4fdd-bb57-cb36c5339a72.png)
![2](https://user-images.githubusercontent.com/78656206/214290314-850c745d-1bd3-41d2-b9ed-f895167765f5.png)

**Comment by Kumar-laxmi** [comment] 2023-01-25 01:43
@kapil4457 Could you implement this in all four languages & under what category should this algorithm be included (Eg: ```Graph``` or ```Sorting```

**Comment by kapil4457** [comment] 2023-01-25 02:48
It is a sorting algorithm implemented on graphs.
I can do this in c++ , c and java.

**Comment by Kumar-laxmi** [comment] 2023-01-26 11:43
I can see that this issue is a duplicate of issue #113

**Closed** 2023-01-26 11:54 UTC
Labels: duplicate
